import Head from 'next/head';
import Sidebar from './components/Sidebar';
import MainScreen from './components/MainScreen';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainScreen />
    </div>
  );
}
